import { motion } from 'framer-motion'
import type { ExplanationSource } from '../types/quiz'

interface AnalysisSummaryProps {
  explanation: string
  source: ExplanationSource
}

function sourceLabel(source: ExplanationSource): string {
  if (source === 'pending') return 'Synthesizing holocron reading...'
  if (source === 'gemini') return 'Holocron analysis generated by Gemini.'
  if (source === 'cache') return 'Holocron analysis served from cache.'
  return 'Fallback deterministic analysis (LLM unavailable).'
}

export function AnalysisSummary({ explanation, source }: AnalysisSummaryProps) {
  const isLoading = source === 'pending'

  return (
    <motion.section
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.45, delay: 0.15 }}
      className="rounded-2xl border border-slate-700/80 bg-slate-900/70 p-6 shadow-[0_0_30px_rgba(56,189,248,0.08)] md:p-8"
    >
      <p className="text-xs uppercase tracking-[0.28em] text-cyan-300/80">Holocron Reading</p>
      <h3 className="mt-1 text-xl font-semibold text-slate-100 md:text-2xl">Analysis Summary</h3>

      {isLoading ? (
        <div className="mt-4 space-y-2">
          <div className="h-4 w-full animate-pulse rounded bg-slate-800/90" />
          <div className="h-4 w-[88%] animate-pulse rounded bg-slate-800/90" />
        </div>
      ) : (
        <p className="mt-4 text-sm leading-relaxed text-slate-200 md:text-base">{explanation}</p>
      )}

      <p className="mt-3 text-[11px] uppercase tracking-widest text-slate-500">
        {sourceLabel(source)}
      </p>
    </motion.section>
  )
}
